/**
 * DRAGON CHASE - Living dragon: cutout rig + laser hunter
 *
 * Rig geometry (layer files, pivots, eye box) is in css/dragon-rig.css,
 * generated by tools/dragon/cut.py. Pure helpers are covered by
 * tests/dragon.test.js; the browser gets everything as window.DragonRig.
 */
(function (root) {
  // Pause between shots: calm field vs someone already in danger
  const SHOT_DELAY_CALM = [7000, 11000];
  const SHOT_DELAY_ALARM = [4000, 7000];

  // Head aim limits: up to 14° up, 6° down — never flips to shoot backwards
  const AIM_UP_DEG = -14;
  const AIM_DOWN_DEG = 6;

  /**
   * Who the dragon shoots: the nearest student ahead of its eye;
   * nobody ahead — the nearest one behind. Dropped and finished are safe.
   * candidates: [{ x, state }], x — avatar centre in track px
   */
  function pickTarget(candidates, eyeX) {
    const prey = candidates.filter(c => c.state !== 'dropped' && c.state !== 'victory');
    if (prey.length === 0) return null;
    const ahead = prey.filter(c => c.x >= eyeX);
    if (ahead.length > 0) return ahead.reduce((a, b) => (b.x < a.x ? b : a));
    return prey.reduce((a, b) => (b.x > a.x ? b : a));
  }

  /**
   * Milliseconds until the next shot; faster once anyone is stressed or bitten
   */
  function shotDelay(states, rand = Math.random) {
    const alarm = states.some(s => s === 'stressed' || s === 'bitten');
    const [min, max] = alarm ? SHOT_DELAY_ALARM : SHOT_DELAY_CALM;
    return Math.round(min + (max - min) * rand());
  }

  /**
   * Head rotation (deg, CSS clockwise) pointing the snout from pivot to target
   */
  function aimAngle(pivot, target) {
    const deg = Math.atan2(target.y - pivot.y, target.x - pivot.x) * 180 / Math.PI;
    return Math.max(AIM_UP_DEG, Math.min(AIM_DOWN_DEG, deg));
  }

  const api = { pickTarget, shotDelay, aimAngle };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  else root.DragonRig = api;
})(typeof window !== 'undefined' ? window : globalThis);
